FROM python:3
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client
WORKDIR /user/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "sh", "/user/src/app/entrypoint.sh" ]